export const APP_NAME = 'Nexa AI Workspace'
export const APP_VERSION = '0.1.0'
export const APP_DESCRIPTION = 'All-in-one AI platform combining chat, code, documents, research, design, and automation.'

export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000'
export const WS_BASE_URL = process.env.NEXT_PUBLIC_WS_URL ?? 'ws://localhost:8000'

export const DEFAULT_MODELS = {
  cheap: 'gpt-4o-mini',
  powerful: 'claude-sonnet-4-20250514',
  code: 'claude-sonnet-4-20250514',
  vision: 'gpt-4o',
  image: 'dall-e-3',
  video: 'runway-gen3',
  audio: 'elevenlabs-multilingual-v2',
  embedding: 'text-embedding-3-small',
} as const

export const PLANS = [
  {
    id: 'free',
    name: 'Free',
    tier: 'free' as const,
    description: 'Perfect for getting started',
    monthlyPrice: 0,
    yearlyPrice: 0,
    features: {
      maxProjects: 3,
      maxChats: 50,
      maxDocuments: 10,
      maxStorage: 100,
      maxTeamMembers: 1,
      allowedModes: ['chat', 'document'],
      maxApiCalls: 100,
      googleIntegration: false,
      obsidianIntegration: false,
      mcpAccess: false,
      desktopApp: false,
      terminalAccess: false,
      computerControl: false,
      imageGeneration: false,
      videoGeneration: false,
      customModels: false,
      apiAccess: false,
      prioritySupport: false,
      auditLogs: false,
    },
    currency: 'USD',
    popular: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    tier: 'pro' as const,
    description: 'For power users and professionals',
    monthlyPrice: 29,
    yearlyPrice: 290,
    features: {
      maxProjects: 20,
      maxChats: 1000,
      maxDocuments: 100,
      maxStorage: 10,
      maxTeamMembers: 1,
      allowedModes: ['chat', 'document', 'ppt', 'code', 'research', 'image', 'teach', 'gem'],
      maxApiCalls: 5000,
      googleIntegration: true,
      obsidianIntegration: true,
      mcpAccess: true,
      desktopApp: true,
      terminalAccess: true,
      computerControl: false,
      imageGeneration: true,
      videoGeneration: false,
      customModels: true,
      apiAccess: true,
      prioritySupport: false,
      auditLogs: false,
    },
    currency: 'USD',
    popular: true,
  },
  {
    id: 'team',
    name: 'Team',
    tier: 'team' as const,
    description: 'Collaborate with your team',
    monthlyPrice: 99,
    yearlyPrice: 990,
    features: {
      maxProjects: 100,
      maxChats: 10000,
      maxDocuments: 500,
      maxStorage: 100,
      maxTeamMembers: 10,
      allowedModes: ['chat', 'document', 'ppt', 'code', 'research', 'image', 'video', 'teach', 'gem', '3d'],
      maxApiCalls: 50000,
      googleIntegration: true,
      obsidianIntegration: true,
      mcpAccess: true,
      desktopApp: true,
      terminalAccess: true,
      computerControl: true,
      imageGeneration: true,
      videoGeneration: true,
      customModels: true,
      apiAccess: true,
      prioritySupport: true,
      auditLogs: true,
    },
    currency: 'USD',
    popular: false,
  },
] as const

export const MODES = [
  { id: 'chat', name: 'Chat', icon: 'MessageSquare', description: 'General AI chat' },
  { id: 'document', name: 'Documents', icon: 'FileText', description: 'Work with documents' },
  { id: 'ppt', name: 'PPTs', icon: 'Presentation', description: 'Create presentations' },
  { id: 'code', name: 'Code', icon: 'Code', description: 'Write and review code' },
  { id: 'research', name: 'Research', icon: 'Search', description: 'Deep research' },
  { id: 'image', name: 'Image', icon: 'Image', description: 'Generate images' },
  { id: 'video', name: 'Video', icon: 'Video', description: 'Generate videos' },
  { id: '3d', name: '3D Design', icon: 'Box', description: '3D modeling and design' },
  { id: 'teach', name: 'Teach', icon: 'GraduationCap', description: 'Learn from documents' },
  { id: 'jarvis', name: 'Jarvis', icon: 'Bot', description: 'Voice assistant mode' },
  { id: 'gem', name: 'Gems', icon: 'Gem', description: 'Custom assistants' },
] as const

export const GEM_TEMPLATES = [
  {
    name: 'Programmer',
    role: 'Software Engineer',
    description: 'Expert coding assistant',
    instructions: 'You are an expert software engineer. Help write, review, and debug code. Suggest best practices and architecture patterns.',
    modelId: 'claude-sonnet-4-20250514',
    icon: 'Code',
    color: '#3B82F6',
  },
  {
    name: 'Designer',
    role: 'UI/UX Designer',
    description: 'Creative design assistant',
    instructions: 'You are a creative designer. Help with UI/UX, color schemes, layouts, and design systems. Provide visual design feedback.',
    modelId: 'gpt-4o',
    icon: 'Palette',
    color: '#EC4899',
  },
  {
    name: 'Researcher',
    role: 'Research Analyst',
    description: 'Deep research assistant',
    instructions: 'You are a research analyst. Find, summarize, and compare sources. Create bibliographies and research reports.',
    modelId: 'gpt-4o',
    icon: 'Search',
    color: '#8B5CF6',
  },
  {
    name: 'Writer',
    role: 'Content Writer',
    description: 'Content creation assistant',
    instructions: 'You are a professional writer. Help write, edit, and improve content. Adapt tone and style as needed.',
    modelId: 'claude-sonnet-4-20250514',
    icon: 'Pen',
    color: '#10B981',
  },
  {
    name: 'Jarvis',
    role: 'Personal Assistant',
    description: 'Your personal AI assistant',
    instructions: 'You are Jarvis, a personal AI assistant. Help manage tasks, schedule, emails, and daily operations. Be proactive and efficient.',
    modelId: 'gpt-4o',
    icon: 'Bot',
    color: '#F59E0B',
  },
  {
    name: 'Professor',
    role: 'Teacher',
    description: 'Educational assistant',
    instructions: 'You are an expert teacher. Explain concepts clearly, create exercises, quizzes, and learning materials. Adapt to the student level.',
    modelId: 'claude-sonnet-4-20250514',
    icon: 'GraduationCap',
    color: '#06B6D4',
  },
]
